### ISSUE TITLE
Метрика

### ISSUE THREAD

**Issue by KochankovID** [KochankovID/Image_processing_laba1#3]
Почему метрика ssim содержит 2 составляющих метрики, где третья (опционально)?

**Comment by ZlobinGM** [comment]
Я её вообще не понял. Вот формула https://ru.wikipedia.org/wiki/SSIM, я делал по ней 1 в 1.

**Comment by ZlobinGM** [comment]
Добавил в PR коммит с 3-ей составляющей, вроде это она.

**Comment by ZlobinGM** [comment]
Добавил 3-ю часть
